[package]
name = "tokio-mavlink"
version = "0.1.0"
edition = "2021"

[dependencies]
futures.workspace = true
mavlink = { workspace = true, features = ["std"] }
thiserror.workspace = true
tokio = { workspace = true, features = [
    "macros",
    "net",
    "sync",
    "time",
    "io-util",
] }
