[package]
name = "floz-replay"
version = "0.1.0"
edition = "2024"
authors = ["Andrew Straw <strawman@astraw.com>"]
description = "Replay centroid data from a .floz file as UDP packets to drive a FLO controller without hardware"

[dependencies]
# deps published on crates.io
clap = { workspace = true, features = ["derive"] }
color-eyre.workspace = true
chrono = { workspace = true, features = ["clock", "std", "serde"] }
serde_yaml.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
tracing-panic.workspace = true

# flo and strand-braid deps
floz-parser.workspace = true
flo-core.workspace = true
