[package]
name = "floz-replay"
version = "0.1.0"
edition = "2024"
authors = ["Andrew Straw <strawman@astraw.com>"]
description = "Replay centroid data from a .floz file through FLO's in-process input"

[dependencies]
# deps published on crates.io
clap = { workspace = true, features = ["derive"] }
color-eyre.workspace = true
chrono = { workspace = true, features = ["clock", "std", "serde"] }
tracing.workspace = true
tokio.workspace = true

# flo and strand-braid deps
floz-parser.workspace = true
flo-core.workspace = true
flo.workspace = true
flo-app.workspace = true

[features]
default = ["bundle_files"]

bundle_files = ["flo/bundle_files"]
serve_files = ["flo/serve_files"]
