[package]
name = "flo-core"
description = "Common definitions"
version = "0.1.0"
authors = ["Andrew Straw <strawman@astraw.com>"]
edition = "2024"

[dependencies]
thiserror.workspace = true
camino.workspace = true
eyre.workspace = true
tracing.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
serde_cbor.workspace = true
tokio = { workspace = true, features = [
    "rt",
    "macros",
    "sync",
], optional = true }
if-addrs = { workspace = true, optional = true }
socket2 = { version = "0.5.5", optional = true }
chrono = { workspace = true, features = ["serde", "clock"] }
nalgebra.workspace = true
adskalman.workspace = true
const_format = { version = "0.2.30", default-features = false }
pwm-motor-types.workspace = true
num = "0.4.3"
num-derive.workspace = true
num-traits.workspace = true
opencv-ros-camera.workspace = true
percent-encoding.workspace = true
cam-geom.workspace = true

strand-cam-remote-control.workspace = true

extended-unified-camera-model = { version = "0.2.0", features = [
    "serde-serialize",
] }

[dev-dependencies]
rand = "0.6.3"
approx.workspace = true
chrono = { workspace = true, default-features = true }
csv.workspace  = true

[features]
default = ["full"]
# `full` includes things that require platform support like the socket2 crate
# and UDP support. These cannot be expected from all platforms with std, such as
# wasm.
full = ["if-addrs", "tokio", "socket2"]
